[package]
name = "rs_minimax"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "tic_tac_toe"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
